---
    name: Build and Push Docker Image
    
    on:
      push:
        tags:
          - 'v*'
    
    env:
      REGISTRY: ${{ secrets.NEXUS_BASEURL }}
      IMAGE_NAME: dataroid/druid-exporter
    
    jobs:
      build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Login to Nexus Registry
            uses: docker/login-action@v3
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
              password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}
    
          - name: Extract tag name
            id: tag
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
          - name: Build Docker image
            run: |
              docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} .
    
          - name: Push Docker image
            run: |
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
